import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Navbar } from "@/app/component/general/Navbar";
import {AuthProvider} from 'app/component/general/AuthProvider.jsx';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "GrowSpace",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <AuthProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased
      max-w-7px mx-auto px-4 sm:px-6 lg:px-8`}
        >
          <Navbar />
          {children}
        </body>
      </html>
    </AuthProvider>
  );
}
